---
title: Talks
page-layout: full
---
- **4 Jan. 2026** — AAS 247 Winter Meeting<br/>
    Phoenix, Arizona<br/>
    [*Correcting photometric observations for cloud extinction using thermal infrared observations*](2026-01-04_AAS247_TALK_KELIAN_SOMMER.pdf)

- **6 Oct. 2025** — Network for Ultraviolet Astronomy (NUVA)<br/>
    Marseille, France<br/>
    [*Characterization and optimization of Skipper CCDs for UV astronomy*]()

- **2 Apr. 2025** — Atmosphere Characterization Workshop<br/>
    La Serena, Chile<br/>
    [*PWV measurements with a GNSS receiver for the StarDICE experiment*](2025-04-01_TALK_Atm_charact_workshop_KELIAN_SOMMER.pdf)

- **17 Jun. 2024** — LUPM Astrophysique Stellaire group meeting<br/>
    Montpellier, France<br/>
    [*High-precision photometry for LSST and ZTF : atmosphere gray extinction characterization with a long-wave infrared instrument within the StarDICE metrology experiment*](2024-06-17_TALK_AS_team_meeting_KELIAN_SOMMER.pdf)

- **23 May 2024** — LSST-DESC Pixel to Light Curves group meeting<br/>
    [*Recent progress of the long-wave infrared instrument for atmosphere gray extinction characterization within the StarDICE experiment*](2024-05-23_TALK_DESC_PixelToLightCurve_group_meeting_KELIAN_SOMMER.pdf)

- **15 Dec. 2023** — Rubin LSST-France meeting<br/>
    CC-IN2P3, Lyon, France<br/>
    [*Recent progress of the long-wave infrared instrument for atmosphere monitoring within the StarDICE experiment*](2023-12-15_TALK_LSST_FRANCE_KELIAN_SOMMER.pdf)

- **7 Dec. 2022** — Journées Scientifiques et Techniques du Laboratoire<br/>
    LUPM, Montpellier, France<br/>
    *Improving photometric calibration for type Ia supernovae cosmology in the era of wide-field surveys with the StarDICE experiment and the CBP instrument*

- **30 Nov. 2022** — IN2P3 School of Instrumentation: "From detector to measurement"<br/>
    Centre CAES, Fréjus, France<br/>
    *Systematic error reduction for type Ia supernovae cosmology with the photometric surveys ZTF and LSST*

- **13 May 2022** — ZTF Spring Meeting<br/>
    LPNHE, Paris, France<br/>
    *Secondary maximum analysis for improved standardization of type Ia supernovae*

# Posters

- **26 Jan. 2022** — *56th Rencontres de Moriond 2022 - Cosmology*  
    La Thuile, Italy  
    *StarDICE: instrumental flux calibration with an artificial star for type Ia supernovae cosmology with the Legacy Survey of Space and Time*
